CREATE TABLE IF NOT EXISTS checkin (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora TIMESTAMP NOT NULL,
    tipo_treino VARCHAR(50) NOT NULL,
    duracao_minutos INTEGER NOT NULL CHECK (duracao_minutos BETWEEN 1 AND 1440),
    intensidade VARCHAR(10) NOT NULL CHECK (intensidade IN ('Leve', 'Moderada', 'Intensa')),
    local_treino VARCHAR(50) NOT NULL,
    dia DATE GENERATED ALWAYS AS (CAST(data_hora AS DATE)),
    CONSTRAINT uk_checkin_dia UNIQUE (dia)
    );
